version: '3.8'

services:
  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geardn_server
    restart: always
    ports:
      - '8080:8080'
    environment:
      - REDIS_HOST=redis_queue
    env_file:
      - .env.production
    depends_on:
      - redis_queue
    networks:
      - backend_net

  # Redis cho Queue/Outbox
  redis_queue:
    image: redis:alpine
    container_name: geardn_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - backend_net

networks:
  backend_net:

volumes:
  redis_data:
