version: '3.9'

services:
  api:
    build: .
    container_name: geardn-api
    restart: always
    env_file:
      - .env.production
    depends_on:
      - redis
    ports:
      - '3000:3000'
    # Nếu bạn dùng Neon/Postgres cloud thì không cần DB container
    # Nếu có queue, cron, Bull đều chạy trong cùng process này

  redis:
    image: redis:7-alpine
    container_name: geardn-redis
    restart: always
    # Không expose ra ngoài Internet, chỉ để internal Docker
    # Nếu cần debug thì có thể mở:
    # ports:
    #   - "6379:6379"
    command: ['redis-server', '--appendonly', 'yes']
